extends: standard
rules:
  camelcase: "off"
  comma-dangle: "off"
  no-return-assign: "warn"
  operator-linebreak: "warn"
  eol-last: "warn"
  space-before-function-paren: "warn"
  space-in-parens: "warn"
  no-multiple-empty-lines: "warn"
  key-spacing: "warn"
